name: ncov_outbreaker
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - aioeasywebdav=2.4.0=py38h578d9bd_1001
  - aiohttp=3.7.4.post0=py38h497a2fe_0
  - amply=0.1.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - atk-1.0=2.36.0=h3371d22_4
  - attmap=0.13.0=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - augur=12.0.0=pyhdfd78af_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcbio-gff=0.6.6=pyh864c0ab_1
  - bcrypt=3.2.0=py38h497a2fe_1
  - binutils_impl_linux-64=2.35.1=h193b22a_2
  - binutils_linux-64=2.35=h67ddf6f_30
  - boto3=1.17.96=pyhd8ed1ab_0
  - botocore=1.20.96=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bwidget=1.9.14=ha770c72_0
  - bx-python=0.8.11=py38h024e602_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.5.30=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - coincbc=2.10.5=hcee13e7_1
  - configargparse=1.4.1=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - curl=7.77.0=hea6ffbf_0
  - cvxopt=1.2.6=py38h3118bd0_0
  - cycler=0.10.0=py_2
  - datrie=0.8.2=py38h497a2fe_2
  - decorator=4.4.2=py_0
  - docutils=0.17.1=py38h578d9bd_0
  - dropbox=11.11.0=pyhd8ed1ab_0
  - dsdp=5.8=hd9d9efa_1203
  - et_xmlfile=1.1.0=py38h06a4308_0
  - expat=2.4.1=h9c3ff4c_0
  - fasttree=2.1.10=h779adbc_5
  - fftw=3.3.9=nompi_hcdd671c_101
  - filechunkio=1.8=py_2
  - filelock=3.0.12=pyh9f0ad1d_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h516909a_0
  - ftputil=5.0.1=pyhd8ed1ab_0
  - gcc_impl_linux-64=9.3.0=h70c0ae5_19
  - gcc_linux-64=9.3.0=hf25ea35_30
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gettext=0.21.0=hf68c758_0
  - gfortran_impl_linux-64=9.3.0=hc4a2995_19
  - gfortran_linux-64=9.3.0=hdc58fab_30
  - ghostscript=9.54.0=h9c3ff4c_1
  - giflib=5.2.1=h516909a_2
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.17=pyhd8ed1ab_0
  - glpk=4.65=h9202a9a_1004
  - gmp=6.2.1=h58526e2_0
  - google-api-core=1.30.0=pyhd8ed1ab_0
  - google-api-python-client=2.9.0=pyhd8ed1ab_0
  - google-auth=1.31.0=pyhd3eb1b0_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_0
  - google-cloud-core=1.7.0=pyh6c4a22f_0
  - google-cloud-storage=1.38.0=pyh44b312d_0
  - google-crc32c=1.1.2=py38h8838a9a_0
  - google-resumable-media=1.3.0=pyh6c4a22f_0
  - googleapis-common-protos=1.53.0=py38h578d9bd_0
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.47.2=h85b4f2f_0
  - grpcio=1.38.0=py38hdd6454d_0
  - gsl=2.6=he838d99_2
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - gxx_impl_linux-64=9.3.0=hd87eabc_19
  - gxx_linux-64=9.3.0=h3fbe746_30
  - harfbuzz=2.8.1=h83ec7ef_0
  - httplib2=0.19.1=pyhd8ed1ab_0
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - imagemagick=7.1.0_0=pl5321hb118871_0
  - importlib-metadata=4.5.0=py38h578d9bd_0
  - importlib_metadata=4.5.0=hd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipython_genutils=0.2.0=py_1
  - iqtree=2.1.2=h56fc30b_0
  - isa-l=2.30.0=ha770c72_4
  - jbig=2.1=h7f98852_2003
  - jdcal=1.4.1=py_0
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py38h32f6830_1
  - jupyter_core=4.7.1=py38h578d9bd_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.19.1=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libcrc32c=1.1.1=he1b5a44_2
  - libcurl=7.77.0=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-devel_linux-64=9.3.0=h7864c58_19
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgd=2.3.2=h78a0170_0
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.3=h3e27bee_0
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=9_openblas
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.15=pthreads_h8fe5266_1
  - libpng=1.6.37=hed695b0_2
  - libprotobuf=3.17.2=h780b84a_0
  - librsvg=2.50.7=hc3c00ef_0
  - libsodium=1.0.18=h516909a_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-devel_linux-64=9.3.0=hb016644_19
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.3.0=hf544144_1
  - libtool=2.4.6=h58526e2_1007
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.2.0=h3452ae3_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h72842e0_0
  - llvm-openmp=8.0.1=hc9558a2_0
  - logmuse=0.2.6=pyh8c360ce_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - lzo=2.10=h516909a_1000
  - mafft=7.480=h779adbc_0
  - make=4.3=hd18ef5c_1
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib-base=3.4.2=py38hcc49a3a_0
  - metis=5.1.0=he1b5a44_1006
  - more-itertools=8.8.0=pyhd8ed1ab_0
  - multidict=5.1.0=py38h497a2fe_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - networkx=2.5.1=pyhd8ed1ab_0
  - numpy=1.20.3=py38h9894fe3_1
  - oauth2client=4.1.3=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openmp=8.0.1=0
  - openpyxl=3.0.7=pyhd3eb1b0_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py38h1abd341_0
  - pango=1.48.5=hb8ff022_0
  - paramiko=2.7.2=pyh9f0ad1d_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.36=h032f7d1_1
  - peppy=0.31.1=pyhd8ed1ab_0
  - perl=5.32.1=0_h7f98852_perl5
  - pigz=2.6=h27826a3_0
  - pillow=8.2.0=py38ha0e1e83_1
  - pip=21.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h516909a_1008
  - pluggy=0.13.1=py38h578d9bd_4
  - ply=3.11=py_1
  - prettytable=2.1.0=pyhd8ed1ab_0
  - protobuf=3.17.2=py38h709712a_0
  - psutil=5.8.0=py38h497a2fe_1
  - pulp=2.4=py38h578d9bd_0
  - py=1.10.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pygraphviz=1.7=py38h0d738da_0
  - pynacl=1.4.0=py38h497a2fe_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py38h578d9bd_3
  - pytest=6.2.4=py38h578d9bd_0
  - python=3.8.10=h49503c6_1_cpython
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=1.0.0=pyhd8ed1ab_0
  - python-isal=0.10.0=py38h497a2fe_0
  - python-lzo=1.12=py38h86e1cee_1003
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_0
  - r-base=4.1.0=h9e01966_1
  - ratelimiter=1.2.0=py38h32f6830_1001
  - raxml=8.2.12=h779adbc_3
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - rsa=4.7.2=pyh44b312d_0
  - s3transfer=0.4.2=pyhd8ed1ab_0
  - scipy=1.6.3=py38h7b17777_0
  - sed=4.8=he412f7d_0
  - setuptools=52.0.0=py38h06a4308_0
  - simplejson=3.17.2=py38h497a2fe_2
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=5.1.0=pyhd8ed1ab_1
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=6.4.1=hdfd78af_0
  - snakemake-minimal=6.4.1=pyhdfd78af_0
  - snp-dists=0.8.2=h5bf99c6_0
  - snp-sites=2.5.1=h5bf99c6_1
  - sqlite=3.35.5=h74cdb3f_0
  - stone=3.2.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - suitesparse=5.7.2=h717dc36_0
  - sysroot_linux-64=2.12=h77966d4_13
  - tbb=2020.3=hfd86e86_0
  - tk=8.6.10=hed695b0_1
  - tktable=2.10=hb7b940f_3
  - toml=0.10.2=pyhd8ed1ab_0
  - toposort=1.6=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.0.5=py_0
  - treetime=0.8.1=pyh3252c3a_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - ubiquerg=0.6.1=pyh9f0ad1d_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - vcftools=0.1.16=h9a82719_5
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3deb0d_0
  - wrapt=1.12.1=py38h497a2fe_3
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xmlrunner=1.7.7=py_0
  - xopen=1.1.0=py38h578d9bd_2
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.5.1=py38h1e0a361_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - biopython==1.79
    - git+git://github.com/matt-sd-watson/FASTAfurious

